# 🗂️ CONFIGURATION PATHS - START_KIT
# Auto-generated by reorganize script

DATA_PATHS = {
    # Raw data
    "raw_videos": "data/raw/raw_videos",
    "raw_videos_mp4": "data/processed/raw_videos_mp4",
    "final_videos": "data/processed/videos_final",
    
    # Annotations
    "annotations": "data/annotations/WLASL_v0.3.json",
    
    # Features
    "features": "data/features/",
    
    # Legacy models
    "legacy_i3d": "legacy/i3d",
    "legacy_tgcn": "legacy/tgcn"
}

MODEL_PATHS = {
    "modern_models": "modern/models/",
    "modern_configs": "modern/configs/"
}
